Home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="home-index"),
    path('about_us/', views.about_us, name="about_us"),
    path('contact/', views.contact, name="contact"),
    path('privacy_policy/', views.privacy_policy, name="privacy_policy"),
    path('terms/', views.terms, name="terms"),
]

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('payment', views.payment, name="payment-step"),
    path('review', views.review, name="review-step"),
    path('confirmation', views.confirmation, name="confirmation-step"),
]

ship_o_cereal/urls.py
from django.views.static import serve
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cereals/', include('cereal.urls')),
    path('', include('Home.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('cart/', include('cart.urls')),
]

cereal/models.py
from django.db import models

# Create your models here.


class CerealCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Cereal(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=9999, blank=True)
    price = models.IntegerField()
    ingredients = models.CharField(max_length=9999)
    weight = models.IntegerField()
    sugar = models.IntegerField()
    category = models.ManyToManyField(CerealCategory)

    def __str__(self):
        return self.name


class CerealImage(models.Model):
    image = models.CharField(max_length=9999)
    cereal = models.ForeignKey(Cereal, on_delete=models.CASCADE)

    def __str__(self):
        return self.image

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from cereal.models import Cereal


class Country(models.Model):
    country = models.CharField(max_length=255)

    def __str__(self):
        return self.country


class Address(models.Model):
    street = models.CharField(max_length=255, null=True)
    house_number = models.IntegerField(null=True)
    postal_code = models.IntegerField(null=True)
    city = models.CharField(max_length=255, null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    order_completed = models.BooleanField(default=False)
    cereal = models.ForeignKey(Cereal, on_delete=models.SET_NULL, null=True)
    order_date_time = models.DateTimeField(auto_now=True)


class OrderItems(models.Model):
    cereal = models.ForeignKey(Cereal, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.IntegerField()

order/forms/address_form.py
from django.forms import ModelForm, widgets
from order.models import Address


class AddressForm(ModelForm):
    class Meta:
        model = Address
        exclude = ['id']
        widgets = {
            'street': widgets.TextInput(attrs={'class': 'form-control'}),
            'house_number': widgets.NumberInput(attrs={'class': 'form-control'}),
            'postal_code': widgets.NumberInput(attrs={'class': 'form-control'}),
            'city': widgets.TextInput(attrs={'class': 'form-control'}),
            'country': widgets.Select(attrs={'class': 'form-control'}),
        }

order/forms/payment_form.py
from django import forms
from django.core.exceptions import ValidationError
from datetime import datetime

MONTH_CHOICES =(
    ("1", "01"),
    ("2", "02"),
    ("3", "03"),
    ("4", "04"),
    ("5", "05"),
    ("6", "06"),
    ("7", "07"),
    ("8", "08"),
    ("9", "09"),
    ("10", "10"),
    ("11", "11"),
    ("12", "12")
)

YEAR_CHOICES =(
    ("1", "2021"),
    ("2", "2022"),
    ("3", "2023"),
    ("4", "2024"),
    ("5", "2025"),
    ("6", "2026"),
    ("7", "2027"),
    ("8", "2028"),
    ("9", "2029"),
    ("10", "2030")
)


def validate_card_number(card_number):
    if len(str(card_number)) != 12:
        raise ValidationError('Card number not valid')


class PaymentForm(forms.Form):
    cardholder_name = forms.CharField(max_length=100)
    card_number = forms.IntegerField()
    expiration_month = forms.ChoiceField(choices=MONTH_CHOICES)
    expiration_year = forms.ChoiceField(choices=YEAR_CHOICES)
    csv = forms.IntegerField()

    def clean_card_number(self):
        card_number = self.cleaned_data["card_number"]
        if len(str(card_number)) != 16:
            raise ValidationError('Card number needs to of length 16')

        return card_number

    def clean_csv(self):
        csv = self.cleaned_data["csv"]
        if len(str(csv)) != 3:
            raise ValidationError('CSV needs to be of length 3')

        return csv

    def clean(self):
        datetime_now = datetime.today()
        exp_month = self.cleaned_data["expiration_month"]
        exp_year = self.cleaned_data["expiration_year"]
        if (2020 + int(exp_year)) <= datetime_now.year and int(exp_month) < datetime_now.month:
            self.add_error('expiration_month', "Card is expired")

order/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from order.forms.address_form import AddressForm
from order.forms.payment_form import PaymentForm
from order.models import Order, Address, Country, OrderItems
from user.models import Profile
from cart.models import Cart, CartCereal
from cart.views import clear_cart

# Create your views here.
from cereal.models import Cereal


@login_required
def payment(request):
    profile = Profile.objects.filter(user=request.user).first()
    address = Address.objects.filter(id=profile.address_id).first()

    if address is None:
        address = Address()
        address.save()

        has_address = False
    else:
        has_address = True

    clear_incomplete_order(request.user)

    new_order = Order(
        order_completed=False,
        address=address,
        user=request.user
    )
    new_order.save()

    copy_cart_to_order(new_order)

    order_items = OrderItems.objects.filter(order=new_order)

    total_price_payment = total_price(order_items)

    if request.method == 'POST':
        address_form = AddressForm(instance=address, data=request.POST)
        payment_form = PaymentForm(data=request.POST)
        if address_form.is_valid() and payment_form.is_valid():
            address = address_form.save()
            new_order.save()

            # Checks if save address to profile was selected and adds the address to user profile
            if request.POST.get('save_address', default=None) == 'on':
                profile.address = address
                profile.save()
            return redirect('review-step')
        else:
            return render(request, 'order/payment.html', {
                'order_items': order_items,
                'address_form': address_form,
                'payment_form': payment_form,
                'total_price': total_price_payment,
                'has_address': has_address
            })

    else:
        address_form = AddressForm(instance=address)  # Attempts to fetch the user profile's address
        payment_form = PaymentForm()
        return render(request, 'order/payment.html', {
            'order_items': order_items,
            'address_form': address_form,
            'payment_form': payment_form,
            'total_price': total_price_payment,
            'has_address': has_address
        })


def copy_cart_to_order(order):
    user_cart = Cart.objects.filter(user=order.user).first()
    user_cart_items = CartCereal.objects.filter(cart=user_cart)
    for user_item in user_cart_items:
        order_item = OrderItems(
            cereal=user_item.cereal,
            order=order,
            quantity=user_item.quantity
        )
        order_item.save()


def clear_incomplete_order(user):
    # Checks if an old order exists in the system, that is not completed. If so it deletes it.
    old_order = Order.objects.filter(user=user, order_completed=False)
    if old_order.exists():
        old_order = old_order.first()
        old_address = Address.objects.filter(id=old_order.address_id).first()
        profile = Profile.objects.filter(user=user).first()
        if profile.address is None:
            old_address.delete()
        old_order.delete()


# Fetches all order data and displays it for confirmation
@login_required
def review(request):
    order = Order.objects.filter(user=request.user, order_completed=False).first()
    items = OrderItems.objects.filter(order=order)
    total_price_review = total_price(items)
    address = order.address

    return render(request, 'order/review.html', {
        'items': items,
        'total_price': total_price_review,
        'address': address,
    })


# Last step in payment, when order has been placed
@login_required
def confirmation(request):
    clear_cart(request)
    try:
        order = get_object_or_404(Order, user=request.user, order_completed=False)
        items = OrderItems.objects.filter(order=order)
        order.order_completed = True  # Changes order status to complete
        order.save()
        return render(request, 'order/confirmation.html', {
            'order': order,
            'items': items
        })
    except:
        return redirect('cereal-index')


def total_price(items):
    price = 0
    for item in items:
        price += item.cereal.price * item.quantity
    return price

templates/order/confirmation.html
{% extends 'base.html' %}
{% block content %}
    <div class="confirmation-step-container">
    <h2>Confirmation step 3/3</h2>
    <div class = "order-confirmation">
        <h4>Order Placed!</h4>
        <p>Order ID: {{ order.id }}</p>
    </div>
    <div class = "order-confirmation-details">
        <h5>Order details</h5>
        {% for item in items %}
            <img class = "checkout-image" src={{ item.cereal.cerealimage_set.first.image }}>
            <p style ='display: inline'> {{ item.cereal }}</p>
            <p style = "float:right">Quantity: {{ item.quantity }}</p>
        {% endfor %}
    </div>
    <a href="{% url 'cereal-index' %}" class="block btn btn-primary">Back to catalog</a>
    </div>
{% endblock %}

templates/order/payment.html
{% extends 'base.html' %}
{% block content %}
    <div class="payment-step-container">
    <h2>Payment step 1/3</h2>
    <div class="order-details">
    <h5>Order details</h5>
    {% for item in order_items %}
        <img class = "checkout-image" src="{{ item.cereal.cerealimage_set.first.image }}" alt="picture of the cereal">
        <p style ='display: inline'> {{ item.cereal }} </p>
        <p style = "float:right">Quantity: {{ item.quantity }}</p>
        <br>
    {% endfor %}
    <br>
    <h6>Total price: {{ total_price }}</h6>
    </div>

    <br>

    <form class="form form horizontal" action="{% url 'payment-step' %}" method="post">
        {% csrf_token %}
        <div class = "address-information">
        <h5>Address information</h5>
        {{ address_form }}
        <div>
        {% if not has_address %}
            <input type="checkbox" name="save_address">
            <label for="save_address">Save address to profile</label>
        {% endif %}
        </div>
        <br>
        </div>
        <div class = "payment-information">
            <h5>Payment information</h5>
        {{ payment_form.as_p}}
        {{ form.non_field_errors}}
            </div>
        <input type="button" value="Back" onclick="history.back()">
        <input style = "float: right" type="submit" value="Continue" class="btn btn-primary" style="clear:both; margin: 10px 0" />

    </form>


    </div>
{% endblock %}

templates/order/review.html
{% extends 'base.html' %}
{% block content %}
    <div class="review-step-container">
    <h2>Review step 2/3</h2>
    <br>
    <div class = "order-details">
    <h5>Order details</h5>
    {% for item in items %}
        <img class = "checkout-image" src="{{ item.cereal.cerealimage_set.first.image }}" alt="picture of the cereal">
         <p style ='display: inline'> {{ item.cereal }}</p>
        <p style = "float:right">Quantity: {{ item.quantity }}</p>
        <br>
    {% endfor %}
    <br>
    <h6>Total price: {{ total_price }} kr</h6>
    </div>
    <br>
    <div class = "address-information">
    <h4>Shipping address</h4>
    <p>Street: {{ address.street }}</p>
    <p>House number: {{ address.house_number }}</p>
    <p>Postal code: {{ address.postal_code }}</p>
    <p>City: {{ address.city }}</p>
    <p>Country: {{ address.country }}</p>
    </div>
    <input type="button" value="Back" onclick="history.back()">
    <a style = "float:right" href="{% url 'confirmation-step' %}" class="block btn btn-primary">Confirm Order</a>
    </div>

{% endblock %}